name: Deployment

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    
jobs:
  deployment-test-US:
    runs-on: ubuntu-22.04
    environment:
      name: test-us
      url: https://google.com
    steps:
      - name: deploy
        # fake step
        uses: actions/checkout@v3

  deployment-test-EU:
    runs-on: ubuntu-22.04
    environment:
      name: test-eu
      url: https://google.com
    steps:
      - name: deploy
        # fake step
        uses: actions/checkout@v3

  deployment-prod-EU:
    runs-on: ubuntu-22.04
    needs: deployment-test-EU
    environment:
      name: prod-eu
      url: https://github.com
    steps:
      - name: deploy
        # fake step
        uses: actions/checkout@v3


  deployment-prod-US:
    runs-on: ubuntu-22.04
    needs: deployment-test-US
    environment:
      name: prod-us
      url: https://github.com
    steps:
      - name: deploy
        # fake step
        uses: actions/checkout@v3