name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment_test:
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://google.com
    steps:
      - name: deploy
        # fake step
        uses: actions/checkout@v3

  deployment_prod:
    runs-on: ubuntu-latest
    needs: deployment_test
    environment:
      name: prod
      url: https://github.com
    steps:
      - name: deploy
        # fake step
        uses: actions/checkout@v3
